
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 396725 bytes/channel
 *	Total Size: 1 * 396725 + 4 (header) = 396769 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mariezimmy/Desktop/Purzzle Music/gameMusic.wav
 *	Time-stamp: Wed Apr 10 18:32:15 2019
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 396725

extern const unsigned char gameMusic[396725];

#endif /* __GAMEMUSICH__ */
