
/**************************************************************
 *	
 *	mainMusic, 8 bit, 11025Hz,
 *	1 channel, 495736 bytes/channel
 *	Total Size: 1 * 495736 + 4 (header) = 495780 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mariezimmy/Desktop/Purzzle Music/mainMusic.wav
 *	Time-stamp: Wed Apr 10 18:32:43 2019
 *	
 **************************************************************/

#ifndef __MAINMUSICH__
#define __MAINMUSICH__

#define MAINMUSICFREQ 11025
#define MAINMUSICLEN 495736

extern const unsigned char mainMusic[495736];

#endif /* __MAINMUSICH__ */
