
/**************************************************************
 *	
 *	meow, 8 bit, 11025Hz,
 *	1 channel, 5258 bytes/channel
 *	Total Size: 1 * 5258 + 4 (header) = 5302 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mariezimmy/Desktop/meow.wav
 *	Time-stamp: Sun Apr 14 19:40:08 2019
 *	
 **************************************************************/

#ifndef __MEOWH__
#define __MEOWH__

#define MEOWFREQ 11025
#define MEOWLEN 5258

extern const unsigned char meow[5258];

#endif /* __MEOWH__ */
