
/**************************************************************
 *	
 *	pauseMusic, 8 bit, 11025Hz,
 *	1 channel, 516432 bytes/channel
 *	Total Size: 1 * 516432 + 4 (header) = 516476 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/mariezimmy/Desktop/Purzzle Music/pauseMusic.wav
 *	Time-stamp: Wed Apr 10 18:33:14 2019
 *	
 **************************************************************/

#ifndef __PAUSEMUSICH__
#define __PAUSEMUSICH__

#define PAUSEMUSICFREQ 11025
#define PAUSEMUSICLEN 516432

extern const unsigned char pauseMusic[516432];

#endif /* __PAUSEMUSICH__ */
